### PR TITLE
Move yanked string to top of kill ring after yanking

### PR DESCRIPTION
**Pull request by YorkZ**
Firstly, thank you so much for this amazing project.

Please review this PR. I bind `M-y` to `consult-yank-pop`, and this change made my life a lot easier because previously when I needed to yank the same content again and again from the kill ring, I had to pick it from the kill ring far away from the top, not to mention that the content would eventually be removed from the kill ring altogether.

### CODE REVIEW

**Comment by minad** [comment]
Thanks. I am not sure about this. We should probably make it configurable. How does this relate to #668 (kill ring rotation)? Ideally we implement a unified solution for #668 which rotates the kill ring (if enabled via an option).

**Comment by YorkZ** [comment]
I'm not sure I understand exactly what #668 means, but I would guess it says the same thing. I think #668 proposed a customizable variable but no implementation yet right? So if you decide to add the customization, the implementation would be similar to this PR right?

**Comment by minad** [comment]
No, I think it would be different. There is some index used to rotate the ring.

**Comment by YorkZ** [comment]
I don't know how `consult` works in this regard. So deleting the entry from the kill ring and killing the content again to bring it to the top doesn't rotate the part of kill ring?

**Comment by minad** [comment]
No, obviously this won't lead to a rotation.

**Comment by minad** [comment]
Close in favor of #682

**Comment by YorkZ** [comment]
OK, thanks @mattiasdrp. Your PR hasn't been merged yet right?

**Comment by mattiasdrp** [comment]
Not yet, I'm starting my journey through fixing issues in emacs packages and there're a lot of things I don't do right :D

**Pull request closed without merging**
