### PR TITLE
Add consult-line-everywhere

### PR DESCRIPTION
**Pull request by minad**
Search in lines across project buffers or all buffers. The name is up to debate.

cc @iyefrat, if you have time to give this a test I would appreciate it.

### CODE REVIEW

**Comment by hmelman** [comment]
I don't have an opinion on the name but for info:

- At least in what I have loaded the only "everywhere" I have is `ido-everywhere`.  
- I have 3 `-all-buffers` commands, for wgrep, tramp and Buffer-menu.  
- Another option is using `multi-` as in `multi-isearch-buffers` and  `multi-occur` 
- Since this is mostly about searching in projects, why not `consult-line-in-project`?

**Comment by minad** [comment]
If a prefix argument is given, the search includes all buffers, not only the project buffers.

**Comment by hmelman** [comment]
> If a prefix argument is given, the search includes all buffers, not only the project buffers.

I saw that, but I think you name a command based on it's default behavior, not based on what happens with an optional argument.  Obviously it's better if you can account for both.

Since it only searches open buffers, `consult-line-in-project` is probably wrong since it implies to me "all project files".  Since this searches several buffers, either those in the same project or all buffers, it seems closest to the "multi" commands.

Would you consider including other groupings of buffers, like all with the same major mode?  I could see that being useful in say all elisp buffers even if they're in different projects.

**Comment by minad** [comment]
> Would you consider including other groupings of buffers, like all with the same major mode? I could see that being useful in say all elisp buffers even if they're in different projects.

Not out of the box, but if you look at the implementation - it uses the `consult--buffer-query` function, which allows to search buffers by multiple criteria. Users can easily write their own command based on these functions.

**Pull request merged**
