### PR TITLE
Handle previews of invisible text

### PR DESCRIPTION
**Pull request by jakanakaevangeli**
Fixes https://github.com/minad/consult/issues/21

### CODE REVIEW

**Comment by minad** [comment]
@jakanakaevangeli Thank you! For now I added the save-excursion fix. I tested this and it works nicely with org mode and outline. However I wonder if it makes sense to generalize this somehow and rather install it via some hooks, maybe also install them by default. The question is if there are other mechanisms which perform hiding/unhiding.

There is consult--jump-1 and the isearch-range-invisible code is always executed after it, so maybe that code could go to the consult-after-jump-hook?

**Comment by minad** [comment]
@jakanakaevangeli See here for the current wip https://github.com/minad/consult/tree/unfolding

**Comment by minad** [comment]
I decided to use the mechanism of ctrlf, which seems cleaner since like this we do not manipulate any global state.

**Comment by jakanakaevangeli** [comment]
Thanks. Congratulations on getting rid of global state.

**Pull request closed without merging**
