### PR TITLE
check marker when looking up imenu item

### PR DESCRIPTION
**Pull request by zbelial**
This PR aims to solve issue #299 , it puts the marker as a text property to each item.

### CODE REVIEW

**Comment by minad** [comment]
This is not a correct patch since completing-read does not retain the properties.

**Comment by zbelial** [comment]
Sorry for making this incorrect patch and thanks for letting me know the reason why it's incorrect. 
I use `ivy-mode`, it sets `completing-read-function` to `ivy-completing-read`, which seems to retain properties, so it worked when I tested this patch.  I forgot to test it with the default `completing-read`. Sorry.

**Comment by minad** [comment]
No worries. I appreciate your bug report and your attempt to fix the issue. Generally try to test your patches with completion systems which are fully supported by Consult (Selectrum, Vertico, Icomplete, default completion). Ivy is not yet supported (#212) as you are aware. Out of interest, which commands do you miss in the Selectrum/Consult/Embark ecosystem in contrast to the Ivy/Counsel set of packages?

**Comment by zbelial** [comment]
> Out of interest, which commands do you miss in the Selectrum/Consult/Embark ecosystem in contrast to the Ivy/Counsel set of packages?

There are several things that are important to me: 
1. Ivy's :preselect, which makes me preselect a item. 
    I'll use `counsel-imenu` as a use case. When I invoke `counsel-imenu` and the cursor is in a function, for example `Func`, I want to preselect it, but not the first one(You know functions that are relevant are close in files, so I can select them more easily).  I use this feature in a command to show pdf files' table of  contents too.
2. If candidates are a list of cons, `ivy-read` will return the whole cons(including properties), not just the car of it.  `consult-imenu` can also benefit from this kind of feature I think. 
3. I can use different filters for different commands. 

These are the features I miss in Consult/Selectrum. 
Maybe ivy's internal is more sophisticated, I find `ivy-read` is powerful and convenient. 

As a user, what I want the most from Consult are preview and narrow, that's the reason why I want to add ivy support to Consult (I wish I can finish it some day, but Emacs completing system is complex for me, and Ivy's internal is really sohisticated).

**Comment by zbelial** [comment]
Actually I wish I can write commands use Emacs completing system's api but not a specific one (such as ivy-read) some day.  And I know you're making some improvement in this aspect (I've seen some patches you commit in emacs mailing list). Thanks.

**Comment by minad** [comment]
I am not sure I understand these points. These are not strong arguments. All of them are possible in Consult/selectrum/vertico, but maybe not in exactly the same form.

1. How is :preselect different from :default which is supported by consult--read and completing-read?
2. If you want conses set the :lookup function to consult--lookup-cons
3. Different completion styles? This is possible by setting completion-category-defaults or completion-category-defaults.

**Comment by zbelial** [comment]
Most ivy commands I use(swiper, counsel-imenu, counsel-outline, counsel-rg, counsel-yank-pop)  have equivalents with similar behaviour in Consult/Selectrum, I've not noticed any significant differences.  I choose ivy because of its api ( I've wrote several commands with it), which I'm more familiar with and is more intuitive IMO.

Actually I don't have enough knowledge of Emacs completion, I've made a little effort to learn it, but I can't say I succeeded.  So, the following examples and explainations may not be corrent/good enough. 

> * How is :preselect different from :default which is supported by consult--read and completing-read?
The following examples can show the difference.  In both examples, do not input anything but just press <return> .
``` elisp 
;; use ivy-read 
(setq r (ivy-read "test: "
         `((,(propertize "foobar1" 'marker "abc") 1) ("barfoo" 2) ("foobaz" 3) ("foobar1" 4) )
         :preselect 0
         ))
=> #("foobar1" 0 7 (marker "abc"))
```

```elisp
;; use completing-read
(setq r (completing-read "Test: "
         '(("foobar1" 1) ("barfoo" 2) ("foobaz" 3) ("foobar1" 4))
         nil nil nil nil "foobar1"
         ))
=> "foobar1"
``` 
With `ivy-read`, you can know exactly which candidate is returned , but with `completing-read`, you have no idea of which "foobar1" it is.  I know you can use, like consult--lookup-cons, to look up the candidate, but you have to deduplicate the candidates, like what you did in `consult-imenu`, to get the exact one. 

> * If you want conses set the :lookup function to consult--lookup-cons.
It has minor drawback as described above. 

> * Different completion styles? This is possible by setting completion-category-defaults or completion-category-defaults, which are an Emacs built-in configuration variables.
I had no idea about this, and I cannot test it right now, but I'll try it. Thanks.

**Comment by minad** [comment]
Okay, your point here is that Ivy supports duplicate items. I made a proposal on emacs-devel to support this duplicates also with `completing-read`, but I am not yet sure if I will proceed with it. Ivy implements this as an extension, which is okay since it uses its own api. The Consult set of packages cannot make use of this functionality since we have to rely on the built-in functionality. I have somehow come to the conclusion that deduplication is not that bad after all (as I did for `consult-imenu`, `consult-line` etc.)

**Comment by zbelial** [comment]
Another thing is `completing-read` does not retain properties(as you pointed out in a previous comment), which ivy supports. It's a useful feature in some cases. 

All in all, ivy is the first completing system I'm familiar with as a user, and I get used to it as a daily toolset. This is the reason why I'm still stick to it now.

**Comment by minad** [comment]
> Another thing is completing-read does not retain properties(as you pointed out in a previous comment), which ivy supports. It's a useful feature in some cases.

This is not really "another thing". It is just the same thing as - the completion system supports duplicates, since string equality does not take properties into account. If `completing-read` would allow duplicates the preservation of text properties would b implied.

> All in all, ivy is the first completing system I'm familiar with as a user, and I get used to it as a daily toolset. This is the reason why I'm still stick to it now.

I understood that. You should stay with it if you like it. I wonder why you are even considering Consult which explicitly does not support Ivy, given that there is Counsel which is a strong library. I guess there is nothing wrong with having multiple libraries installed doing similar things, many people have both Helm and Ivy installed for example. But there is also a large group of people who somehow try to use a streamlined Emacs, with a focus on minimalism and consistency.

**Comment by zbelial** [comment]
> I wonder why you are even considering Consult which explicitly does not support Ivy, given that there is Counsel which is a strong library.

I'd like to try out new good packages, so I installed Selectrum and then Consult when I found them. And I like Consult's narrow and preview(I found preview is pretty useful when I want to have a quick look at the content of a buffer or a function but don't want to switch to it).  I'm one of the people who have Helm and Ivy (and Consult) installed at the same time.

**Pull request closed without merging**
