### PR TITLE
Experiment with cheap markers

### PR DESCRIPTION
**Pull request by minad**
Fix for #517

@oantolin What do you think about the change? The complexity of the change is not that high. It may help if one repeatedly executes `consult-line` on larger files. In embark-consult you could use `consult--location-marker` to access the markers.

### CODE REVIEW

**Comment by minad** [comment]
Okay, I cleaned this up a little bit more. To access the location data in Embark, simply use `consult--get-location` instead of `get-text-property`. Then you will get these lazily upgraded markers. I think this is a good change

**Comment by oantolin** [comment]
Yes, it looks good, and fairly simple.

But I think this means that for embark-export and embark-collect I should evaluate `consult--get-location` on each candidate at collect/export time. Waiting until the user presses RET on each candidate is too late as a lot of other editing could happen in between. Now, for export this is fine, I can just do it in the exporter, but for collect I think there isn't currently a hook where I could do this. I need to think a bit how best to do it.

**Comment by minad** [comment]
> But I think this means that for embark-export and embark-collect I should evaluate consult--get-location on each candidate at collect/export time. Waiting until the user presses RET on each candidate is too late as a lot of other editing could happen in between. Now, for export this is fine, I can just do it in the exporter, but for collect I think there isn't currently a hook where I could do this. I need to think a bit how best to do it.

Hmm, note that Consult also tries to upgrade markers in a window selection change hook. Not sure if this is already sufficient for embark collect?

**Comment by oantolin** [comment]
> Not sure if this is already sufficient for embark collect?

I think it probably won't run, because embark-collect/export quit the minibuffer before they display the collect/export buffer, so the unwind-protect probably removes the hook before the hook can run. But I'm not sure, I'll test.

**Comment by oantolin** [comment]
Oh, I just realized there is a good place to upgrade markers during collect: `embark-collect-mode-hook`!

**Comment by minad** [comment]
Okay, I think from the side of Consult this is ready. We should synchronize our efforts a bit to avoid unnecessary breakage for MELPA users. Do you want me to prepare a PR for Embark or do you already have something in the works. You probably know better where to perform the upgrade?

**Comment by oantolin** [comment]
I handle things in embark-consult.

**Comment by oantolin** [comment]
I'm almost done. Embark collect is slightly tricky: I'm trying to only upgrade the markers when necessary, and the case where you use `embark-collect-live` is causing a bit of trouble.

**Comment by minad** [comment]
I thought about this too, but I would say that any special casing is unnecessary. First you won't do worse than we already do. Second live collect will only open up after you typed a few characters or on demand. At this point the set of candidates will already be reduced such that the issue is less pronounced. Then we are already doing better than before. Therefore I would not do anything special and keep thing simple on the side of Embark.

**Comment by oantolin** [comment]
OK, sounds reasonable.

**Comment by oantolin** [comment]
Mmh. Choosing a consult-line candidate from the embark-collect-completions buffer is broken right now, but that's unrelated to this issue (to make sure it's unrelated I tested from my normal configuration without this branch of consult).

**Comment by minad** [comment]
That's good if we also fix some other issues on the go :)

**Comment by oantolin** [comment]
OK, I made a cheap-markers branch of embark. I'll fix that bug separately.

**Comment by minad** [comment]
Okay, great. It looks simple on the side of Embark! I merge this then.

**Comment by oantolin** [comment]
OK, I'll merge too.

**Comment by oantolin** [comment]
Done.

**Comment by oantolin** [comment]
And that bug I noticed is fixed now: oantolin/embark@98bdc0f553d5bf0caa2c5acf828c3a8d99a5f231. It was a simple oversight: Embark collect buffers now remove the tofu and stash the original candidate in a text property, but when I made that change I forgot to update the function called when you press RET on a candidate and it was using the tofuless candidate in the embark-completions case.

**Comment by oantolin** [comment]
I forgot to say: the only reason I didn't notice that earlier is that I switched to Vertico full time!

**Comment by minad** [comment]
MELPA already picked our changes up. It seems we merged just in time! :smile:

**Comment by oantolin** [comment]
That was lucky.

**Pull request merged**
