### PR TITLE
consult-bookmark: Fix creating bookmarks and add more handlers

### PR DESCRIPTION
**Pull request by clemera**
Thank you very much for implementing it here are my suggestions for more narrowing prefixes. Also creation of bookmarks when providing a non existing name did not work.

### CODE REVIEW

**Comment by minad** [comment]
@clemera Thanks! Are these all standard bookmarks? Will some of those work as fast preview? Just file/position markers or are they all more sophisticated such that we cannot easily preview them. In order to perform preview one could also just run the bookmark jump, but then this might have bad side effects and performance issues. For this reason I only perform the preview when I know well what is going to happen or when I control it.

**Comment by clemera** [comment]
Yes these are are from Emacs core. I don't think preview works when there is a handler, I did not test it (I generally don't use automatic preview) but there is a comment that only bookmarks without a handler are previewed.

**Comment by clemera** [comment]
Yes these are are from Emacs core. I haven't looked into if they could be make work with preview (I generally don't use automatic preview). I would be interested in a manual option so I can press a key and preview the candidate.

**Comment by minad** [comment]
Manual preview is just an Embark action I guess? Do you use no preview at all? For example there is also the yank preview.

**Comment by clemera** [comment]
I use the regular yank-pop usually, could I add an embark action which uses the consult preview?

**Comment by minad** [comment]
No preview is not an action. I meant in order to manually preview you could just execute the default action. This would work with consult-buffer. But then you don't get the auto closing behavior of temporary preview buffers as in consult-grep for example. Maybe it really makes sense to add a consult specific action which triggers the preview.

**Comment by clemera** [comment]
Actually having auto preview for consult yank only would be nice, I haven't really setup consult for my purposes, yet.

**Comment by minad** [comment]
@clemera Okay. Right now it is possible to enable preview globally and then disable it per action. Probably it would be nice to define the default preview mode globally (off, auto, manual) and per command. The manual mode would then require a keybinding in the minibuffer map.

**Comment by clemera** [comment]
Does it need to be mode? Maybe it could just be a variable?

**Comment by minad** [comment]
See #143, Maybe continue the discussion there. Yes it has originally been a mode since I did some setup. This is gone now but I have been hesitant to make it a variable in order to avoid breakage. When or if #143 comes we could break it and we necessarily have. Then it should also be a variable.

**Comment by clemera** [comment]
Okay nice, thanks!

**Pull request merged**
