### PR TITLE
Delay mode hooks when previewing files

### LINKED ISSUE #515: Defer loading major mode, or exclude certain modes on preview
Hi there, dropping a quick issue as I was thinking about a problem that I usually have when using the live-preview feature. Normally I have it off, as I believe sometimes it slows down my Emacs considerably.

An example of this is when previewing a file which has a major mode that is controlled by lsp-mode. The live-preview loads the major mode and lsp-mode, which causes the language server initialization. For heavy-handed servers, this process is slow, and I find myself waiting for the server to initialize, even if I wasn't planning on opening that file.

I have a couple suggestions:
- The problem that I see with deferring the major mode is that the preview will have no syntax highlighting.
- Maybe there could be a variable for major modes that should be taken care of differently (for previews), even if the candidate list is the same. This would probably mean having control over the candidates individually, but I don't find this to be a problem as we are already doing that when building the candidate list.

I created this issue to start a discussion, what do you think? Have you already sunk some time thinking about this topic?

### PR DESCRIPTION
**Pull request by astoff**
Fixes #515.

This will skip running all mode hooks, including say the activation of a language server or starting a Flyspell process. If desired, we could run some of the `delayed-mode-hooks` based on a whitelist or blacklist. But I don't think this is actually necessary.

### CODE REVIEW

**Comment by minad** [comment]
I am unsure. This feels like a sledgehammer method. Note that previewed buffers will stick around if you modify them. These buffers are then in a half initialized state. Wouldn't it be better to filter out only certain problematic hooks? Another possibility could be to finish the delayed initialization here by invoking `run-mode-hooks`:

https://github.com/minad/consult/blob/47c4f405efdf4692c6b7e1dd2098573db9aeae6c/consult.el#L1142

(We could also discuss to just remove file preview and other problematic previews altogether and only use explicit Embark non quitting actions for "preview". There seem to be too many issues around this preview feature. It may be more reasonable to only preview things which are already available (buffers, kill ring entries, etc.) but nothing else.)

**Comment by astoff** [comment]
> Note that previewed buffers will stick around if you modify them. These buffers are then in a half initialized state.

Don't they already end up in a half-initialized state, since you skip the dir-local variables and some find-file-hooks?

How about making the preview buffers read-only, and recklessly killing them in the end?

> Lsp certainly is a problem but these cases could be configured one by one.

Then in any case you have to delay the mode hooks, then look at `delayed-mode-hooks` and pick whatever you want from there.
Personally, I'm happy to sledgehammer the problem away, but maybe some people will want to configure things.

> We could also discuss to just remove file preview

I guess the problem is not the file preview, but calling a major mode just for the sake of coloring some words? I think the preview is genuinely useful.

**Comment by minad** [comment]
Hmm. I have to think about this more. Not sure if you saw the addition of `consult--with-location-upgrade`?

https://github.com/minad/consult/blob/47c4f405efdf4692c6b7e1dd2098573db9aeae6c/consult.el#L917-L932

Maybe an approach like this could work too. We start with buffer where everything is disabled. But as soon as the user moves out of the minibuffer we kill all previewed, unmodified and invisible buffers and finish the delayed initialization of the visible buffers.

**Comment by astoff** [comment]
Well, I don't know what you think of the idea of #538, but that makes it totally impossible to finish a delayed initialization. (And how do you finish up adding the dir-locals and the skipped find-file-hooks?)

I'm more inclined to declare that you can't edit a _file_ preview (_buffer_ preview is fine), so make it read-only.

**Comment by minad** [comment]
> I'm more inclined to declare that you can't edit a file preview (buffer preview is fine), so make it read-only.

I want to preserve recursive editing.

> Well, I don't know what you think of the idea of https://github.com/minad/consult/issues/538, but that makes it totally impossible to finish a delayed initialization. (And how do you finish up adding the dir-locals and the skipped find-file-hooks?)

I have yet to understand what the essence is of #538. Finishing dir-locals and skipped hooks are indeed an issue. A possible solution could be to kill the previewed (read-only/delayed) buffer and reopen it when moving to recursive editing. Then we could just skip everything during preview and still get a perfectly initialized buffer as soon as we edit recursively.

**Comment by astoff** [comment]
> A possible solution could be to kill the previewed (read-only/delayed) buffer and reopen it when moving to recursive editing.

Yes, this sounds like a feasible approach.

**Comment by astoff** [comment]
By the way, in the snippet at https://github.com/minad/consult/pull/542#issuecomment-1075611465, why do you create a symbol and fset to it? `add-hook` and `remove-hook` can handle lambdas just fine. (Of course I wouldn't add a lambda to permanently to some hook, I'm only talking about this recurse edit kind of situation.)

**Comment by minad** [comment]
> add-hook and remove-hook can handle lambdas just fine.

Oh they don't. First there is a debugging issue if these hook lists are blown up with large closures. But more significantly there was a serious issue where `add-hook` and `remove-hook` led to expensive equality checks if hook priorities are used (affects Emacs 27 and older). Note that `add-hook`/`remove-hook` use `equal` to check hooks for equality. This problem occurs only if you use large closures - Consult produces very large closures in `consult--read`. Unfortunately this even affects `minibuffer-with-setup-hook` with `:append`:

https://github.com/minad/consult/blob/473e6585c516d0e7fd4c256c333713fb40e9947a/consult.el#L703-L723

Furthermore there was a memory leak issue if local hooks with priorities are used (affects both Emacs 27 and 28). For this reason, local hooks with priorities should never be used, but there are also not many reasons to use local hooks with priorities. However see here for a use case in Consult:

https://github.com/minad/consult/blob/473e6585c516d0e7fd4c256c333713fb40e9947a/consult.el#L1341-L1348

Anyway it took quite some time to figure out these issues, mitigate them and fix them upstream. Therefore I ended up with using only symbols for hooks in Consult. In some of the cases I could change the hooks back to use lambdas.

**Comment by minad** [comment]
To be clear: The expensive closure equality check should be fixed in 28. This means we can use lambdas as global hooks with or without priorities. Local hooks with priorities are still broken on 28 and should not be used - not even with symbols, since this will still lead to a memory leak. These are fixed on 29. So it seems that finally in Emacs 29 the basic `add-hook` and `remove-hook` APIs do the right thing for all arguments. :laughing:

**Comment by astoff** [comment]
That very good to know, since I'm adding a lambda to a hook in the lazy-highlight for query-replace which is under discussion in the bug tracker.

Another fun fact, hashing of byte-compiled closures is broken in Emacs ≤ 27. Hence this:

https://github.com/astoff/devdocs.el/blob/beaf3584e18e9359181b9a9cdc57cfce0d7724e7/devdocs.el#L106-L124

**Comment by minad** [comment]
I think in upstream it doesn't matter since you can rely on the fixed APIs. 

(Unrelated but I think I will drop Emacs 26 support from my packages now, so see if people are still using that. It should be a big issue since Vertico also requires Emacs 27. Besides these hook issues and some other smaller issues, Emacs 27 was mostly robust for me so I think I will support 27 for longer. But bugs in basic APIs are really the worst :-P).

**Pull request closed without merging**
