### PR TITLE
Add annotation for consult-org-heading

### PR DESCRIPTION
**Pull request by ashton314**
I would like being able to see the TODO state and the priority of each headline when using `consult-org-heading`. This PR adds an annotation function.

I tried to follow the style of some of the annotation functions I found in consult and marginalia. That said, I'm sure work remains on this PR. :) I figured I'd send the thing I got working NOW and get some feedback/help faster.

Thanks!

### CODE REVIEW

**Comment by minad** [comment]
I merged this a bit too quickly. Did you assign the copyright to the FSF for your Emacs contributions, have you signed the papers?

**Comment by ashton314** [comment]
Ah, shoot. I’ll get that signed today if I can.

**Comment by ashton314** [comment]
Signed and sent. Also got an employer waiver from my advisor 👍🏼

**Comment by ashton314** [comment]
@minad I got the confirmation back! Merge away!

**Pull request merged**
